# install.packages("sf", lib = "~/bsh_ISDM/R_packages") # already downloaded in the FARM
# install.packages("tidyverse", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("raster", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("zoo", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("here", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("dismo", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("rgdal", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("rgeos", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("remotes", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("Metrics", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("caret", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# remotes::install_version("INLA", version="22.05.07",repos="https://inla.r-inla-download.org/R/stable", dep=TRUE, lib = "~/bsh_ISDM/R_packages")
# library(remotes, lib.loc = "~/bsh_ISDM/R_packages")
# remotes::install_version("INLA", version="22.05.07",repos="https://inla.r-inla-download.org/R/testing", dep=TRUE, lib = "~/bsh_ISDM/R_packages")
# install.packages('https://cran.r-project.org/src/contrib/Archive/inlabru/inlabru_2.7.0.tar.gz', repos=NULL, type="source", lib = "~/bsh_ISDM/R_packages")
# install.packages('https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.5-4.tar.gz', repos=NULL, type="source", lib = "~/bsh_ISDM/R_packages")
# library(remotes, lib.loc = "~/bsh_ISDM/R_packages")
# install.packages("https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.5-4.tar.gz", repos=NULL, type = 'source')
# install.packages("terra", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("sn", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
# install.packages("ecospat", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")
install.packages("fmesher", repos = "http://cran.us.r-project.org", lib = "~/bsh_ISDM/R_packages")

#library(terra)
print(sessionInfo())